project:
  type: book

book:
  title: "Geospatial Data Science with Julia"
  cover-image: "images/cover.svg"
  author: "Júlio Hoffimann"
  date: today
  chapters:
    - index.qmd
    - foreword.qmd
    - preface.qmd
    - 1-geodata.qmd
    - 2-geoviz.qmd
    - 3-geoio.qmd
    - 4-feattrans.qmd
    - 5-geomtrans.qmd
    - 6-bothtrans.qmd
    - 7-splitcombine.qmd
    - 8-geojoins.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: solar
  pdf:
    documentclass: scrreprt

jupyter: julia-1.9