project:
  type: book

book:
  title: "Geospatial Data Science with Julia"
  cover-image: "images/cover.svg"
  author: "Júlio Hoffimann"
  date: today
  chapters:
    - index.qmd
    - 0-preface.qmd
    - 1-introduction.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt

jupyter: julia-1.9