project:
  type: book

book:
  title: "Geospatial Data Science with Julia"
  cover-image: "images/cover.svg"
  author: "Júlio Hoffimann"
  date: today
  chapters:
    - index.qmd
    - foreword.qmd
    - preface.qmd
    - part: "Part I: Foundations"
      chapters:
        - 1-geodata.qmd
        - 2-geoviz.qmd
        - 3-geoio.qmd
        - 4-geoproc.qmd
    - part: "Part II: Transforms"
      chapters:
        - 5-transforms.qmd
        - 6-projections.qmd
        - 7-pipelines.qmd
    - part: "Part III: Queries"
      chapters:
        - 8-splitcombine.qmd
        - 9-geojoins.qmd
    - part: "Part IV: Applications"
      chapters:
        - 10-agriculture.qmd
        - 11-mining.qmd
        - 12-energy.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: solar
  pdf:
    documentclass: scrreprt

jupyter: julia-1.9